__merge__: ../api/comp_process_dataset.yaml
functionality:
  name: "process_dataset"
  resources:
    - type: python_script
      path: script.py
    - path: limma_contrast.r
    - path: limma_fit.r
    - path: limma_utils.py
    - path: utils.py
  test_resources:
    - type: bash_script
      path: test.sh
    - path: resources/neurips-2023-data
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: python
        packages: [ anndata, pandas, numpy, scipy ]
      - type: r
        bioc: [ edgeR, limma ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
