__merge__: ../api/comp_process_dataset.yaml
functionality:
  name: "process_dataset"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
